import { Product, TestPlan, Requirement, TestCase } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "E-Commerce Platform",
    repoUrl: "https://github.com/company/ecommerce",
    description: "Main e-commerce platform for online shopping",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "prod-2",
    name: "Mobile App",
    repoUrl: "https://github.com/company/mobile-app",
    description: "iOS and Android mobile application",
    createdAt: new Date("2024-02-20"),
  },
];

export const mockTestPlans: TestPlan[] = [
  {
    id: "tp-1",
    productId: "prod-1",
    featureName: "User Authentication",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "tp-2",
    productId: "prod-1",
    featureName: "Shopping Cart",
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "tp-3",
    productId: "prod-2",
    featureName: "Push Notifications",
    createdAt: new Date("2024-02-25"),
  },
  {
    id: "tp-4",
    productId: "prod-2",
    featureName: "Offline Mode",
    createdAt: new Date("2024-03-01"),
  },
];

export function getProducts(): Product[] {
  return mockProducts;
}

export function getProductById(id: string): Product | undefined {
  return mockProducts.find((product) => product.id === id);
}

export function getTestPlansByProductId(productId: string): TestPlan[] {
  return mockTestPlans.filter((testPlan) => testPlan.productId === productId);
}

export function getTestPlanById(id: string): TestPlan | undefined {
  return mockTestPlans.find((testPlan) => testPlan.id === id);
}

// Mock Requirements and Test Cases based on the PRD
export const mockRequirements: Requirement[] = [
  {
    id: "req-1",
    number: "FR-001",
    type: "functional",
    description: "The system shall allow users to upload PRD documents in PDF format",
    testCases: [
      {
        id: "tc-1",
        requirementId: "req-1",
        description: "Verify user can successfully upload a valid PDF document",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "integration"],
      },
      {
        id: "tc-2",
        requirementId: "req-1",
        description: "Verify system rejects non-PDF file uploads",
        isPositive: false,
        isNegative: true,
        testTypes: ["unit", "security"],
      },
      {
        id: "tc-3",
        requirementId: "req-1",
        description: "Verify system handles large PDF files (up to 50MB)",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "system"],
      },
      {
        id: "tc-4",
        requirementId: "req-1",
        description: "Verify system displays appropriate error message for corrupted PDF files",
        isPositive: false,
        isNegative: true,
        testTypes: ["integration", "usability"],
      },
      {
        id: "tc-5",
        requirementId: "req-1",
        description: "Verify upload progress indicator displays during file upload",
        isPositive: true,
        isNegative: false,
        testTypes: ["usability", "acceptance"],
      },
    ],
  },
  {
    id: "req-2",
    number: "FR-002",
    type: "functional",
    description: "Users must be able to view a list of all uploaded documents with their upload dates and processing status",
    testCases: [
      {
        id: "tc-6",
        requirementId: "req-2",
        description: "Verify document list displays all uploaded documents",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "integration"],
      },
      {
        id: "tc-7",
        requirementId: "req-2",
        description: "Verify document list shows correct upload dates in readable format",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "usability"],
      },
      {
        id: "tc-8",
        requirementId: "req-2",
        description: "Verify processing status is accurately displayed for each document",
        isPositive: true,
        isNegative: false,
        testTypes: ["integration", "system"],
      },
      {
        id: "tc-9",
        requirementId: "req-2",
        description: "Verify empty state message displays when no documents are uploaded",
        isPositive: true,
        isNegative: false,
        testTypes: ["usability", "acceptance"],
      },
      {
        id: "tc-10",
        requirementId: "req-2",
        description: "Verify document list handles pagination for large number of documents",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "system"],
      },
    ],
  },
  {
    id: "req-3",
    number: "FR-003",
    type: "functional",
    description: "The system shall support document deletion functionality",
    testCases: [
      {
        id: "tc-11",
        requirementId: "req-3",
        description: "Verify user can successfully delete a document",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "integration"],
      },
      {
        id: "tc-12",
        requirementId: "req-3",
        description: "Verify confirmation dialog appears before document deletion",
        isPositive: true,
        isNegative: false,
        testTypes: ["usability", "acceptance"],
      },
      {
        id: "tc-13",
        requirementId: "req-3",
        description: "Verify system prevents deletion of documents currently being processed",
        isPositive: false,
        isNegative: true,
        testTypes: ["integration", "system"],
      },
      {
        id: "tc-14",
        requirementId: "req-3",
        description: "Verify deleted document is removed from the document list",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "integration"],
      },
      {
        id: "tc-15",
        requirementId: "req-3",
        description: "Verify system handles deletion errors gracefully",
        isPositive: false,
        isNegative: true,
        testTypes: ["integration", "system"],
      },
    ],
  },
  {
    id: "req-4",
    number: "FR-004",
    type: "functional",
    description: "The system shall automatically process uploaded PRD documents using an AI agent",
    testCases: [
      {
        id: "tc-16",
        requirementId: "req-4",
        description: "Verify processing automatically starts after document upload",
        isPositive: true,
        isNegative: false,
        testTypes: ["integration", "system"],
      },
      {
        id: "tc-17",
        requirementId: "req-4",
        description: "Verify processing stages are tracked and displayed to user",
        isPositive: true,
        isNegative: false,
        testTypes: ["integration", "usability"],
      },
      {
        id: "tc-18",
        requirementId: "req-4",
        description: "Verify system handles processing failures and displays error messages",
        isPositive: false,
        isNegative: true,
        testTypes: ["system", "reliability"],
      },
      {
        id: "tc-19",
        requirementId: "req-4",
        description: "Verify processing completes within expected time frame",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "acceptance"],
      },
      {
        id: "tc-20",
        requirementId: "req-4",
        description: "Verify system prevents duplicate processing of the same document",
        isPositive: true,
        isNegative: false,
        testTypes: ["integration", "system"],
      },
    ],
  },
  {
    id: "req-5",
    number: "FR-005",
    type: "functional",
    description: "The system shall extract all functional requirements from PRD documents",
    testCases: [
      {
        id: "tc-21",
        requirementId: "req-5",
        description: "Verify all functional requirements are extracted from PRD document",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "integration"],
      },
      {
        id: "tc-22",
        requirementId: "req-5",
        description: "Verify extracted requirements have unique identifiers",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "system"],
      },
      {
        id: "tc-23",
        requirementId: "req-5",
        description: "Verify system handles PRD documents with no functional requirements",
        isPositive: false,
        isNegative: true,
        testTypes: ["integration", "system"],
      },
      {
        id: "tc-24",
        requirementId: "req-5",
        description: "Verify extracted requirements are clear, testable, and specific",
        isPositive: true,
        isNegative: false,
        testTypes: ["acceptance", "usability"],
      },
      {
        id: "tc-25",
        requirementId: "req-5",
        description: "Verify requirement extraction handles various PRD document formats",
        isPositive: true,
        isNegative: false,
        testTypes: ["compatibility", "system"],
      },
    ],
  },
  {
    id: "req-6",
    number: "FR-006",
    type: "functional",
    description: "The system shall extract all non-functional requirements including performance, security, usability, and scalability requirements",
    testCases: [
      {
        id: "tc-26",
        requirementId: "req-6",
        description: "Verify all non-functional requirements are extracted from PRD document",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "integration"],
      },
      {
        id: "tc-27",
        requirementId: "req-6",
        description: "Verify performance requirements are correctly identified and extracted",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "system"],
      },
      {
        id: "tc-28",
        requirementId: "req-6",
        description: "Verify security requirements are correctly identified and extracted",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "security"],
      },
      {
        id: "tc-29",
        requirementId: "req-6",
        description: "Verify usability and scalability requirements are correctly extracted",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "system"],
      },
      {
        id: "tc-30",
        requirementId: "req-6",
        description: "Verify system distinguishes between functional and non-functional requirements",
        isPositive: true,
        isNegative: false,
        testTypes: ["integration", "system"],
      },
    ],
  },
  {
    id: "req-7",
    number: "FR-007",
    type: "functional",
    description: "The system shall automatically generate test cases for each extracted requirement",
    testCases: [
      {
        id: "tc-31",
        requirementId: "req-7",
        description: "Verify test cases are generated for each extracted requirement",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "integration"],
      },
      {
        id: "tc-32",
        requirementId: "req-7",
        description: "Verify generated test cases are specific and actionable",
        isPositive: true,
        isNegative: false,
        testTypes: ["acceptance", "usability"],
      },
      {
        id: "tc-33",
        requirementId: "req-7",
        description: "Verify system generates test cases even for complex requirements",
        isPositive: true,
        isNegative: false,
        testTypes: ["system", "integration"],
      },
      {
        id: "tc-34",
        requirementId: "req-7",
        description: "Verify test case generation fails gracefully when requirement is unclear",
        isPositive: false,
        isNegative: true,
        testTypes: ["system", "reliability"],
      },
      {
        id: "tc-35",
        requirementId: "req-7",
        description: "Verify generated test cases reference their source requirements",
        isPositive: true,
        isNegative: false,
        testTypes: ["unit", "integration"],
      },
    ],
  },
  {
    id: "req-8",
    number: "NFR-001",
    type: "non-functional",
    description: "The system shall respond to user requests within 2 seconds under normal load conditions",
    testCases: [
      {
        id: "tc-36",
        requirementId: "req-8",
        description: "Verify document list page loads within 2 seconds",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "system"],
      },
      {
        id: "tc-37",
        requirementId: "req-8",
        description: "Verify document upload API responds within 2 seconds",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "integration"],
      },
      {
        id: "tc-38",
        requirementId: "req-8",
        description: "Verify system fails performance test when response time exceeds 2 seconds",
        isPositive: false,
        isNegative: true,
        testTypes: ["performance", "system"],
      },
      {
        id: "tc-39",
        requirementId: "req-8",
        description: "Verify response time remains under 2 seconds with 50 concurrent users",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "load"],
      },
      {
        id: "tc-40",
        requirementId: "req-8",
        description: "Verify system handles response time degradation gracefully under high load",
        isPositive: false,
        isNegative: true,
        testTypes: ["performance", "stress"],
      },
    ],
  },
  {
    id: "req-9",
    number: "NFR-002",
    type: "non-functional",
    description: "The system shall handle at least 100 concurrent users without performance degradation",
    testCases: [
      {
        id: "tc-41",
        requirementId: "req-9",
        description: "Verify system handles 100 concurrent users without errors",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "load"],
      },
      {
        id: "tc-42",
        requirementId: "req-9",
        description: "Verify system performance degrades gracefully beyond 100 concurrent users",
        isPositive: false,
        isNegative: true,
        testTypes: ["performance", "stress"],
      },
      {
        id: "tc-43",
        requirementId: "req-9",
        description: "Verify system maintains response times under 100 concurrent user load",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "load"],
      },
      {
        id: "tc-44",
        requirementId: "req-9",
        description: "Verify system handles concurrent document uploads from multiple users",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "integration"],
      },
      {
        id: "tc-45",
        requirementId: "req-9",
        description: "Verify system prevents resource exhaustion under concurrent load",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "security"],
      },
    ],
  },
  {
    id: "req-10",
    number: "NFR-003",
    type: "non-functional",
    description: "Document processing shall complete within 5 minutes for documents up to 50 pages",
    testCases: [
      {
        id: "tc-46",
        requirementId: "req-10",
        description: "Verify 10-page document processing completes within 5 minutes",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "system"],
      },
      {
        id: "tc-47",
        requirementId: "req-10",
        description: "Verify 50-page document processing completes within 5 minutes",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "system"],
      },
      {
        id: "tc-48",
        requirementId: "req-10",
        description: "Verify system fails when processing exceeds 5 minutes for 50-page document",
        isPositive: false,
        isNegative: true,
        testTypes: ["performance", "system"],
      },
      {
        id: "tc-49",
        requirementId: "req-10",
        description: "Verify processing time scales linearly with document size",
        isPositive: true,
        isNegative: false,
        testTypes: ["performance", "system"],
      },
      {
        id: "tc-50",
        requirementId: "req-10",
        description: "Verify system provides progress updates during long processing times",
        isPositive: true,
        isNegative: false,
        testTypes: ["usability", "acceptance"],
      },
    ],
  },
  {
    id: "req-11",
    number: "NFR-004",
    type: "non-functional",
    description: "The system shall authenticate users before allowing document uploads or access to documents",
    testCases: [
      {
        id: "tc-51",
        requirementId: "req-11",
        description: "Verify authenticated users can upload documents",
        isPositive: true,
        isNegative: false,
        testTypes: ["security", "integration"],
      },
      {
        id: "tc-52",
        requirementId: "req-11",
        description: "Verify unauthenticated users cannot upload documents",
        isPositive: false,
        isNegative: true,
        testTypes: ["security", "integration"],
      },
      {
        id: "tc-53",
        requirementId: "req-11",
        description: "Verify unauthenticated users cannot access document details",
        isPositive: false,
        isNegative: true,
        testTypes: ["security", "system"],
      },
      {
        id: "tc-54",
        requirementId: "req-11",
        description: "Verify authentication tokens are validated on each request",
        isPositive: true,
        isNegative: false,
        testTypes: ["security", "integration"],
      },
      {
        id: "tc-55",
        requirementId: "req-11",
        description: "Verify system handles expired authentication tokens gracefully",
        isPositive: false,
        isNegative: true,
        testTypes: ["security", "usability"],
      },
    ],
  },
  {
    id: "req-12",
    number: "NFR-005",
    type: "non-functional",
    description: "The system shall validate uploaded files to ensure they are valid PDF documents",
    testCases: [
      {
        id: "tc-56",
        requirementId: "req-12",
        description: "Verify system accepts valid PDF files",
        isPositive: true,
        isNegative: false,
        testTypes: ["security", "integration"],
      },
      {
        id: "tc-57",
        requirementId: "req-12",
        description: "Verify system rejects files with PDF extension but invalid format",
        isPositive: false,
        isNegative: true,
        testTypes: ["security", "system"],
      },
      {
        id: "tc-58",
        requirementId: "req-12",
        description: "Verify system validates PDF file structure and headers",
        isPositive: true,
        isNegative: false,
        testTypes: ["security", "unit"],
      },
      {
        id: "tc-59",
        requirementId: "req-12",
        description: "Verify system prevents malicious file uploads disguised as PDFs",
        isPositive: false,
        isNegative: true,
        testTypes: ["security", "system"],
      },
      {
        id: "tc-60",
        requirementId: "req-12",
        description: "Verify system displays clear error message for invalid PDF files",
        isPositive: true,
        isNegative: false,
        testTypes: ["usability", "acceptance"],
      },
    ],
  },
];

export function getMockRequirements(): Requirement[] {
  return mockRequirements;
}
